language: clojure
install:
   - cd daemon; lein deps; cd ..
   - cd client; lein deps; cd ..
# TODO: Add naive benchmark tests
script:
  - test/integration.sh
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - bc
